// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: libs/WitWizCl/Sources/WitWizCl/witwiz.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - witwiz.WitWiz

/// Namespace containing generated types for the "witwiz.WitWiz" service.
internal enum Witwiz_WitWiz {
    /// Service descriptor for the "witwiz.WitWiz" service.
    internal static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "witwiz.WitWiz")
    /// Namespace for method metadata.
    internal enum Method {
        /// Namespace for "JoinGame" metadata.
        internal enum JoinGame {
            /// Request type for "JoinGame".
            internal typealias Input = Witwiz_PlayerInput
            /// Response type for "JoinGame".
            internal typealias Output = Witwiz_GameStateUpdate
            /// Descriptor for "JoinGame".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "witwiz.WitWiz"),
                method: "JoinGame"
            )
        }
        /// Descriptors for all methods in the "witwiz.WitWiz" service.
        internal static let descriptors: [GRPCCore.MethodDescriptor] = [
            JoinGame.descriptor
        ]
    }
}

extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "witwiz.WitWiz" service.
    internal static let witwiz_WitWiz = GRPCCore.ServiceDescriptor(fullyQualifiedService: "witwiz.WitWiz")
}

// MARK: witwiz.WitWiz (server)

extension Witwiz_WitWiz {
    /// Streaming variant of the service protocol for the "witwiz.WitWiz" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    internal protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "JoinGame" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Witwiz_PlayerInput` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Witwiz_GameStateUpdate` messages.
        func joinGame(
            request: GRPCCore.StreamingServerRequest<Witwiz_PlayerInput>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Witwiz_GameStateUpdate>
    }

    /// Service protocol for the "witwiz.WitWiz" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    internal protocol ServiceProtocol: Witwiz_WitWiz.StreamingServiceProtocol {
        /// Handle the "JoinGame" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Witwiz_PlayerInput` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Witwiz_GameStateUpdate` messages.
        func joinGame(
            request: GRPCCore.StreamingServerRequest<Witwiz_PlayerInput>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Witwiz_GameStateUpdate>
    }

    /// Simple service protocol for the "witwiz.WitWiz" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    internal protocol SimpleServiceProtocol: Witwiz_WitWiz.ServiceProtocol {
        /// Handle the "JoinGame" method.
        ///
        /// - Parameters:
        ///   - request: A stream of `Witwiz_PlayerInput` messages.
        ///   - response: A response stream of `Witwiz_GameStateUpdate` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        func joinGame(
            request: GRPCCore.RPCAsyncSequence<Witwiz_PlayerInput, any Swift.Error>,
            response: GRPCCore.RPCWriter<Witwiz_GameStateUpdate>,
            context: GRPCCore.ServerContext
        ) async throws
    }
}

// Default implementation of 'registerMethods(with:)'.
extension Witwiz_WitWiz.StreamingServiceProtocol {
    internal func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: Witwiz_WitWiz.Method.JoinGame.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Witwiz_PlayerInput>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Witwiz_GameStateUpdate>(),
            handler: { request, context in
                try await self.joinGame(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
extension Witwiz_WitWiz.ServiceProtocol {
}

// Default implementation of methods from 'ServiceProtocol'.
extension Witwiz_WitWiz.SimpleServiceProtocol {
    internal func joinGame(
        request: GRPCCore.StreamingServerRequest<Witwiz_PlayerInput>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Witwiz_GameStateUpdate> {
        return GRPCCore.StreamingServerResponse<Witwiz_GameStateUpdate>(
            metadata: [:],
            producer: { writer in
                try await self.joinGame(
                    request: request.messages,
                    response: writer,
                    context: context
                )
                return [:]
            }
        )
    }
}

// MARK: witwiz.WitWiz (client)

extension Witwiz_WitWiz {
    /// Generated client protocol for the "witwiz.WitWiz" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    internal protocol ClientProtocol: Sendable {
        /// Call the "JoinGame" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request producing `Witwiz_PlayerInput` messages.
        ///   - serializer: A serializer for `Witwiz_PlayerInput` messages.
        ///   - deserializer: A deserializer for `Witwiz_GameStateUpdate` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func joinGame<Result>(
            request: GRPCCore.StreamingClientRequest<Witwiz_PlayerInput>,
            serializer: some GRPCCore.MessageSerializer<Witwiz_PlayerInput>,
            deserializer: some GRPCCore.MessageDeserializer<Witwiz_GameStateUpdate>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Witwiz_GameStateUpdate>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "witwiz.WitWiz" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    internal struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        internal init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "JoinGame" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request producing `Witwiz_PlayerInput` messages.
        ///   - serializer: A serializer for `Witwiz_PlayerInput` messages.
        ///   - deserializer: A deserializer for `Witwiz_GameStateUpdate` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        internal func joinGame<Result>(
            request: GRPCCore.StreamingClientRequest<Witwiz_PlayerInput>,
            serializer: some GRPCCore.MessageSerializer<Witwiz_PlayerInput>,
            deserializer: some GRPCCore.MessageDeserializer<Witwiz_GameStateUpdate>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Witwiz_GameStateUpdate>) async throws -> Result
        ) async throws -> Result where Result: Sendable {
            try await self.client.bidirectionalStreaming(
                request: request,
                descriptor: Witwiz_WitWiz.Method.JoinGame.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
extension Witwiz_WitWiz.ClientProtocol {
    /// Call the "JoinGame" method.
    ///
    /// - Parameters:
    ///   - request: A streaming request producing `Witwiz_PlayerInput` messages.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func joinGame<Result>(
        request: GRPCCore.StreamingClientRequest<Witwiz_PlayerInput>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Witwiz_GameStateUpdate>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        try await self.joinGame(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Witwiz_PlayerInput>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Witwiz_GameStateUpdate>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
extension Witwiz_WitWiz.ClientProtocol {
    /// Call the "JoinGame" method.
    ///
    /// - Parameters:
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - producer: A closure producing request messages to send to the server. The request
    ///       stream is closed when the closure returns.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func joinGame<Result>(
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        requestProducer producer: @Sendable @escaping (GRPCCore.RPCWriter<Witwiz_PlayerInput>) async throws -> Void,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Witwiz_GameStateUpdate>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.StreamingClientRequest<Witwiz_PlayerInput>(
            metadata: metadata,
            producer: producer
        )
        return try await self.joinGame(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}